### ISSUE TITLE
Serial is broken - I think

### ISSUE THREAD

**Issue by callen5914** [sheaffej/roboclaw_driver#5]
I just setup a fresh R-Pi and downloaded this repo and downloaded dependencies. When I launch it breaks.

`Unicode Strings are not supported, please encode to bytes '\x80'`

Any ideas?

**Comment by Timple** [comment]
Sounds like a python2 / python3 thingy? Might help you narrow the search for solutions

**Comment by callen5914** [comment]
> Sounds like a python2 / python3 thingy? Might help you narrow the search for solutions

It sure is! It looks like I will need to rewrite this package to support Python 3 which is suitable for Noetic. This will be an undertaking and a half.

Cheers.

**Comment by Timple** [comment]
Or go straight for ROS2 😉

**Comment by callen5914** [comment]
I reverted to using 18.04 on everything so this now works by USB serial only.
