### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by edwardfqj** [sheaffej/roboclaw_driver#8]
When I enter my username and password I get the message:
remote: Repository not found.
fatal: repository 'https://github.com/sheaffej/roboclaw_driver.git/' not found

**Comment by sheaffej** [comment]
@edwardfqj , sorry I had renamed the repo to indicate it was for ROS1 and not ROS2. But in hind sight, I decided that's not a good idea, so I just renamed it back.

Please try again. Thanks for reporting.

**Comment by edwardfqj** [comment]
Thanks it works
